name: site CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Compilar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v4

      - name: Teste Simples
        run: echo "Pipeline funcionando"

      - name: Login no Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Criar imagem no Docker
        run: docker build -t caiodevone/sitedevone:latest .
